
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/codegangsta/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.3"

[[constraint]]
  branch = "master"
  name = "github.com/dutchcoders/durable"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.4"

[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/nu7hatch/gouuid"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "gopkg.in/olivere/elastic.v5"
  version = "5.0.66"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"
